version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails db:prepare && rails s -b 0.0.0.0"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=f1_tracker_development

volumes:
  pgdata:
